# Generated by Django 5.1.2 on 2025-04-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmlocationidentification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
