# Generated by Django 5.1.2 on 2025-05-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmlocationidentification', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmreport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='farmreport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
    ]
