# Generated by Django 5.1.2 on 2025-05-20 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherprediction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('location_name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('temperature_c', models.FloatField()),
                ('condition_text', models.CharField(max_length=100)),
                ('icon_url', models.URLField()),
                ('cloud', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_kph', models.FloatField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('pressure_mb', models.FloatField()),
                ('feelslike_c', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
