# Generated by Django 5.1.2 on 2025-05-11 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafDiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaf_disease_images/')),
                ('predicted_class', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('description', models.TextField()),
                ('care', models.TextField()),
                ('treatment', models.TextField()),
                ('recommended_pesticides_or_fungicides', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
