# Generated by Django 5.1.2 on 2025-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilprediction',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
